#!/usr/bin/env ruby

require 'json'

def puts! a, b=''
  puts "+++ +++ #{b}:"
  puts a.inspect
end

if ARGV.length != 1
  puts ""
  puts "+++ +++ Usage:"
  puts "  ./script/link_peer_dependencies <project-name>"
  puts "Project names: guydjs , iron_warbler , scratchpadjs ."
  puts ""
  exit -3
end

host_path = "/Users/piousbox/projects/node/#{ARGV[0]}"

json = JSON.parse(File.read('package.json'))
json['peerDependencies'].each do |d|
  d = d[0]
  cmd = "rm -rfv node_modules/#{d}"
  puts! cmd, 'cmd'
  `#{cmd}`
  cmd = "ln -sv #{host_path}/node_modules/#{d} node_modules"
  puts! cmd, 'cmd'
  `#{cmd}`
end

