#!/usr/bin/env ruby

def puts! a, b=''
  puts "+++ +++ #{b}:"
  puts a.inspect
end

require 'json'

host_path = '/Users/piousbox/projects/ruby/microsites3/iron_warbler'

json = JSON.parse(File.read('package.json'))
json['peerDependencies'].each do |d|
  d = d[0]
  cmd = "rm -rfv node_modules/#{d}"
  puts! cmd, 'cmd'
  `#{cmd}`
  cmd = "ln -sv #{host_path}/node_modules/#{d} node_modules"
  puts! cmd, 'cmd'
  `#{cmd}`
end

